import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Progress } from "./ui/progress";
import { Users, GraduationCap, TrendingUp, Download, AlertTriangle, BookOpen } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from "recharts";
import { api } from "../api";

const COLORS = ["#18181b", "#52525b", "#a1a1aa", "#d4d4d8"];

export function AdminDashboard() {
  const [dashboard, setDashboard] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { api.get("/dashboard/admin").then(({ data }) => setDashboard(data)).catch(() => setError("System analytics could not be loaded. Please refresh and try again.")); }, []);
  const exportSystemReport = () => {
    if (!dashboard) return;
    const report = { generatedAt: new Date().toISOString(), overview: { totalStudents: dashboard.totalStudents, totalFaculty: dashboard.totalFaculty, activeClasses: dashboard.activeClasses, overallAttendance: dashboard.overallAttendance }, departments: dashboard.departments, atRiskStudents: dashboard.atRiskStudents, topClasses: dashboard.topClasses };
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: "application/json" })); link.download = `attendance-system-report-${new Date().toISOString().split("T")[0]}.json`; link.click(); URL.revokeObjectURL(link.href);
  };
  if (!dashboard && !error) return <div className="py-12 text-center text-muted-foreground">Loading system analytics...</div>;
  if (!dashboard) return <div className="py-12 text-center text-destructive">{error}</div>;
  return <div className="space-y-6">
    <div className="flex justify-between items-start"><div><h2 className="text-2xl font-semibold">System Administration</h2><p className="text-muted-foreground">Monitor and manage the attendance system</p></div><Button onClick={exportSystemReport}><Download className="h-4 w-4 mr-2"/>Export Report</Button></div>
    {error && <p className="rounded-md border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[["Total Students", dashboard.totalStudents.toLocaleString(), GraduationCap], ["Total Faculty", dashboard.totalFaculty, Users], ["Active Classes", dashboard.activeClasses, BookOpen], ["System Attendance", `${dashboard.overallAttendance}%`, TrendingUp]].map(([label,value,Icon]) => <Card key={label}><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div><Icon className="h-8 w-8 text-primary"/></div></CardContent></Card>)}</div>
    <Tabs defaultValue="analytics" className="space-y-4"><TabsList><TabsTrigger value="analytics">Analytics</TabsTrigger><TabsTrigger value="departments">Departments</TabsTrigger><TabsTrigger value="alerts">Alerts & Reports</TabsTrigger></TabsList>
      <TabsContent value="analytics" className="space-y-4"><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader><CardTitle>Monthly Attendance Trend</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={300}><LineChart data={dashboard.monthlyAttendance}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis domain={[0,100]}/><Tooltip/><Line type="monotone" dataKey="attendance" stroke="#18181b" strokeWidth={2}/></LineChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Attendance Distribution</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={dashboard.distribution} cx="50%" cy="50%" outerRadius={100} dataKey="value" label={({ value }) => `${value}%`}>{dashboard.distribution.map((entry,index) => <Cell key={entry.name} fill={COLORS[index]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></CardContent></Card></div>
        <Card><CardHeader><CardTitle>Top Performing Classes</CardTitle></CardHeader><CardContent>{dashboard.topClasses.length ? <div className="space-y-4">{dashboard.topClasses.map((course) => <div key={course.className} className="flex items-center justify-between p-4 border rounded-lg"><div><h3 className="font-medium">{course.className}</h3><p className="text-sm text-muted-foreground">{course.faculty}</p></div><Badge>{course.attendance}%</Badge></div>)}</div> : <p className="py-4 text-center text-sm text-muted-foreground">Completed attendance sessions are needed to rank classes.</p>}</CardContent></Card>
      </TabsContent>
      <TabsContent value="departments" className="space-y-4"><Card><CardHeader><CardTitle>Department Overview</CardTitle></CardHeader><CardContent>{dashboard.departments.length ? <ResponsiveContainer width="100%" height={400}><BarChart data={dashboard.departments}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="attendance" fill="#18181b"/></BarChart></ResponsiveContainer> : <p className="py-4 text-center text-sm text-muted-foreground">No department data is available.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Department Statistics</CardTitle></CardHeader><CardContent><div className="space-y-6">{dashboard.departments.map((department) => <div key={department.name} className="space-y-2"><div className="flex justify-between items-center"><h3 className="font-medium">{department.name}</h3><div className="text-right"><p className="text-sm text-muted-foreground">{department.students} students • {department.faculty} faculty</p><p className="font-medium">{department.attendance}% attendance</p></div></div><Progress value={department.attendance} className="h-2"/></div>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="alerts" className="space-y-4"><Card><CardHeader><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-destructive"/><CardTitle>At-Risk Students</CardTitle><Badge variant="destructive">{dashboard.atRiskStudents.length}</Badge></div></CardHeader><CardContent>{dashboard.atRiskStudents.length ? <div className="space-y-4">{dashboard.atRiskStudents.map((student) => <div key={student.id} className="flex items-center justify-between p-4 border rounded-lg border-destructive/20 bg-destructive/5"><div><h3 className="font-medium">{student.name}</h3><p className="text-sm text-muted-foreground">{student.id} • {student.department}</p></div><div className="text-right"><Badge variant="destructive">{student.attendance}%</Badge><p className="mt-1 text-sm text-muted-foreground">{student.classesAttended}/{student.totalClasses} classes</p></div></div>)}</div> : <p className="py-4 text-center text-sm text-muted-foreground">No students are currently below the 75% attendance threshold.</p>}</CardContent></Card><Card><CardHeader><CardTitle>System Activity</CardTitle></CardHeader><CardContent><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="p-4 border rounded-lg"><p className="text-sm text-muted-foreground">Active QR Codes</p><p className="mt-1 text-lg font-semibold">{dashboard.activeQrCodes}</p></div><div className="p-4 border rounded-lg"><p className="text-sm text-muted-foreground">Daily Scans</p><p className="mt-1 text-lg font-semibold">{dashboard.dailyScans}</p></div></div></CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}
